### ISSUE TITLE
Test vector upper bits are wrong

### ISSUE THREAD

**Issue by maroonbells** [jslicer/FNV-1a#3]
My calculations of test vectors are different than this produces
1. 128/256/512 vectors for empty string are 1 digit too long with extra leading zero. The 32/64 vectors all include the 0x prefix in their output, which none of the longer vectors do.
2. 256: 1st hex digit should be 6 not 0 for 'a'
3. 256: 1st hex digit should be B not 0 for 'foobar'
4. 512: 1st hex digit should be E not 0 for 'a'
5. 512: 1st hex digit should be B not 0 for 'foobar'
7. 1024: because all vectors begin with several 0's, you need to calculate vector for longer string to identify whether this length also has error in upper 4 bits. 1024-bit Vector for 12-byte string 'foobarfoobar' should be:
AE859E431319EC6FCAC09E933C0A78B0DE0034ABA17059C38C44AD716D5CC5E39CF72EAE2A383F05369E7B00000000000000000000000000000000000000000000000000000000000000000000000000039C23A21AA5D3091842860BFE6A06043AF9EAC81BA7FC86C4B91E118DB9E2F02514EB4B5F24BBB23B09FF27B0D670DB

**Comment by jslicer** [comment]
Thank you, fixed!
