### ISSUE TITLE
128bit variant returns 17 byte array

### ISSUE THREAD

**Issue by Flavelius** [jslicer/FNV-1a#6]
Hi,
As the title says the 128bit type returns an array of length 17 instead of 16.
This is due to the mod value having 33 characters instead of 32 in the constructors bigint Parse().

And btw, what is the license for the code?

**Comment by jslicer** [comment]
Hello! Thank you for reaching out to me. Would you be so kind as provide a repeatable example I can test against? My unit tests and test vector generators don't seem to exhibit that behavior. Thanks!

**Comment by Flavelius** [comment]
Out of my head, this should do it:
`new Fnv1a128().ComputeHash(System.Text.Encoding.UTF8.GetBytes("Hello World")).Length == 16`
In my case it was a variable length input string, where i needed the resulting hash byte array length to be exactly 16, but it consistently returned 17. It only improved when i removed one of the 0s in the Fnv128:base bigint parsing constructor for the mod value parameter, to make that length 32, which somewhat made sense to me to not be 33.

```
public Fnv1a128() : base(
            Parse("10000000000000000000000000000000", AllowHexSpecifier, InvariantCulture), // <--here
            Parse("0000000001000000000000000000013B", AllowHexSpecifier, InvariantCulture),
            Parse("6C62272E07BB014262B821756295C58D", AllowHexSpecifier, InvariantCulture),
            128)
        {
        [...]

```

**Comment by jslicer** [comment]
Appreciate the input and I just pushed up the fix(es) and some enhancements too.
