### ISSUE TITLE
How to change FnvPrime and FnvOffsetBasis

### ISSUE THREAD

**Issue by Bluscream** [jslicer/FNV-1a#7]
I need these:
```cs
private const UInt32 FnvPrime = 0xB3CB2E29;
private const UInt32 FnvOffsetBasis = 0x319712C3;
```
https://github.com/jslicer/FNV-1a/blob/master/Fnv1a/Fnv1a32.cs#L29C9-L29C36

**Comment by jslicer** [comment]
I've declined the pull request and authored what you asked for but for all the different variants (i.e. keep the interface consistent).
